# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-12 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='read_list',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriptions',
            field=models.CharField(default='', max_length=200),
        ),
    ]
